sudo: false
language: perl
perl:
  - '5.28'
  - '5.26'
  - '5.24'
  - '5.22'
  - '5.20'
  - '5.18'
  - '5.16'
  - '5.14'
install:
  - curl -sL --compressed https://git.io/cpm | perl - install -g
before_script:
  - git clone https://github.com/exercism/problem-specifications.git
  - bin/fetch-configlet
script:
  - bin/configlet lint .
  - prove exercises/*/.meta/solutions/
    --recurse
    --directives
    --jobs 2
  - prove t/
    --directives
